//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceFinder.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class SageUserSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SageUserSettings defaultInstance = ((SageUserSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SageUserSettings())));
        
        public static SageUserSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal baseCurrCode {
            get {
                return ((decimal)(this["baseCurrCode"]));
            }
            set {
                this["baseCurrCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4905")]
        public decimal carrNomCode {
            get {
                return ((decimal)(this["carrNomCode"]));
            }
            set {
                this["carrNomCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public decimal stockNomCode {
            get {
                return ((decimal)(this["stockNomCode"]));
            }
            set {
                this["stockNomCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SageConecto")]
        public string sageAccDSN {
            get {
                return ((string)(this["sageAccDSN"]));
            }
            set {
                this["sageAccDSN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("270978")]
        public string sagePassword {
            get {
                return ((string)(this["sagePassword"]));
            }
            set {
                this["sagePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("manager")]
        public string sageUsername {
            get {
                return ((string)(this["sageUsername"]));
            }
            set {
                this["sageUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal taxCode {
            get {
                return ((decimal)(this["taxCode"]));
            }
            set {
                this["taxCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal taxCodeForeign {
            get {
                return ((decimal)(this["taxCodeForeign"]));
            }
            set {
                this["taxCodeForeign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ProgramData\\Sage\\Accounts\\2017\\Company.000\\ACCDATA")]
        public string sageDBDir {
            get {
                return ((string)(this["sageDBDir"]));
            }
            set {
                this["sageDBDir"] = value;
            }
        }
    }
}
